on:
  push:
    branches:
      - master
    paths:
      - rtl/**
      - tests/**
      - .github/workflows/test-rtl.yml
  workflow_dispatch:

env:
  VERILATOR_CMD: verilator --cc --exe --build -j 0 -Wall

jobs:
  test-rtl:
    runs-on: linux-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test oneshot
        run:  |
              $VERILATOR_CMD tests/oneshot.cpp rtl/oneshot/oneshot.v
              obj_dir/Voneshot

      - name: Lint tft_ili9341
        run:  |
              verilator --lint-only -j 0 -Wall rtl/tft_ili9341/* rtl/bit_reverser/bit_reverser.v

      - name: Test axi_fifo_sequencer
        run:  |
              $VERILATOR_CMD tests/axi_fifo_sequencer.cpp rtl/axi_fifo_sequencer/axi_fifo_sequencer.v
              obj_dir/Vaxi_fifo_sequencer

      - name: Test axi_pixel_fifo
        run:  |
              $VERILATOR_CMD tests/axi_pixel_fifo.cpp rtl/axi_pixel_fifo/axi_pixel_fifo.v
              obj_dir/Vaxi_pixel_fifo

      - name: Test bit_reverser
        run:  |
              $VERILATOR_CMD tests/bit_reverser.cpp rtl/bit_reverser/bit_reverser.v
              obj_dir/Vbit_reverser

      - name: Test gpio74hc595
        run:  |
              $VERILATOR_CMD tests/gpio74hc595.cpp rtl/gpio74hc595/gpio74hc595.v
              obj_dir/Vgpio74hc595
